# Model Training

### scikit - learn

https://scikit-learn.org/stable/

scikitlearn (sklearn) provides simple and efficient tools for predictive data analysis. It is built on NumPy, SciPy, and matplotlib.

First thing, Import all the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', 50)
 # import linear regression model
from sklearn.linear_model import LinearRegression
# import module for train test split
from sklearn.model_selection import train_test_split

In [2]:
# next load the data
df = pd.read_csv('final.csv')
df.head()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
0,295850,2013,234,81,1,1,584,2013,0,0,0,1,0,1
1,216500,2006,169,51,1,1,612,1965,0,0,0,0,41,1
2,279900,2012,216,74,1,1,615,1963,0,0,0,1,49,1
3,379900,2005,265,92,1,1,618,2000,33541,1,0,0,5,0
4,340000,2002,88,30,1,1,634,1992,0,0,0,0,10,1

In [3]:
df.tail()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
1855,760000,2008,881,249,5,5,7842,2003,436035,1,0,0,5,0
1856,690000,2015,1553,473,5,6,6501,1956,23086,1,0,0,59,0
1857,600000,1999,942,287,5,6,7064,1995,217800,1,0,0,4,0
1858,759900,2009,803,245,5,6,7500,2006,8886,1,0,0,3,0
1859,735000,2015,1459,444,5,6,7515,1958,10497,1,0,0,57,0

In [4]:
df.shape

(1860, 14)

## Linear Regression Model

In [5]:
# seperate input features in x
x = df.drop('price', axis=1) # axis=1 will drop a column.

# store the target variable in y
y = df['price']

**Train Test Split**
* Training sets are used to fit and tune your models.
* Test sets are put aside as "unseen" data to evaluate your models.
* The `train_test_split()` function splits data into randomized subsets.

## First Train / Test split

In [6]:
# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, stratify=x.property_type_Condo)

In [7]:
x_train.property_type_Condo.value_counts()

property_type_Condo
0    1208
1     280
Name: count, dtype: int64

In [8]:
x_test.property_type_Condo.value_counts()

property_type_Condo
0    302
1     70
Name: count, dtype: int64

In [9]:
x_train.head()

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
169,2006,265,92,2,2,915,2005,183387,1,1,0,1,0
1751,2010,495,151,5,4,3560,2009,6664,1,0,1,1,0
467,2007,245,75,3,2,1362,1963,0,0,0,0,44,1
1357,2005,558,193,4,3,3022,1935,5000,1,0,0,70,0
146,2002,198,56,2,1,1185,1953,15681,1,0,0,49,0

## Size of each Vector

In [10]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1488, 13), (1488,), (372, 13), (372,))

## Build Linear Regression model on Training set

In [10]:
# train your model
model = LinearRegression()
lrmodel = model.fit(x_train, y_train)

In [11]:
lrmodel.coef_

array([ 8.02467533e+03, -3.21974967e+00,  1.47973972e+03, -1.11040497e+03,
        2.17794801e+03,  1.37960233e+01,  4.50270618e+03,  1.18231433e-01,
        1.31385540e+04,  6.79044387e+03, -4.42760228e+04,  3.52196915e+03,
       -1.31385540e+04])

In [12]:
lrmodel.intercept_

np.float64(-24931634.897010233)

In [13]:
x_train.head(1)

,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
691,2003,352,100,3,2,3187,1975,160736,1,0,0,28,0

## Now Make predictions on Training Set

In [14]:
# make preditions on train set
train_pred = lrmodel.predict(x_train)

In [15]:
train_pred

array([357225.45773619, 338482.11127531, 298975.53409741, ...,
       399495.46500911, 397634.53098914, 657564.55488503], shape=(1488,))

## Compute the Model Error

In [16]:
# evaluate your model
# we need mean absolute error
from sklearn.metrics import mean_absolute_error

train_mae = mean_absolute_error(train_pred, y_train)
print('Train error is', train_mae)

Train error is 83375.54260464183

## Now Make predictions on Test Set

In [ ]:
# make predictions on test set
ypred = lrmodel.predict(x_test)

#evaluate the model
test_mae = mean_absolute_error(ypred, y_test)
print('Test error is', test_mae)

### Our model is still not good beacuse we need a model with Mean Absolute Error < $70,000

Note - We have not scaled the features and not tuned the model.

## Random Forest Model

In [ ]:
# import decision tree model
from sklearn.ensemble import RandomForestRegressor

In [ ]:
# create an instance of the model
rf = RandomForestRegressor(n_estimators=200, criterion='absolute_error')

In [ ]:
# train the model
rfmodel = rf.fit(x_train,y_train)

In [ ]:
# make prediction on train set
ytrain_pred = rfmodel.predict(x_train)

In [ ]:
# make predictions on the x_test values
ytest_pred = rfmodel.predict(x_test)

In [ ]:
# evaluate the model
test_mae = mean_absolute_error(ytest_pred, y_test)
test_mae

In [ ]:
# Individual Decision Trees
# tree.plot_tree(rfmodel.estimators_[2], feature_names=dtmodel.feature_names_in_)

## Pickle:

* The pickle module implements a powerful algorithm for serializing and de-serializing a Python object structure.

* The saving of data is called Serialization, and loading the data is called De-serialization.

**Pickle** model provides the following functions:
* **`pickle.dump`** to serialize an object hierarchy, you simply use `dump()`.
* **`pickle.load`** to deserialize a data stream, you call the `loads()` function.

In [ ]:
# import pickle to save model
import pickle

# Save the trained model on the drive
pickle.dump(dtmodel, open('RE_Model','wb'))

In [ ]:
# Load the pickled model
RE_Model = pickle.load(open('RE_Model','rb'))

np.array(xtrain.loc[22])
ytrain[22]

In [ ]:
# Use the loaded pickled model to make predictions
RE_Model.predict([[2012, 216, 74, 1 , 1, 618, 2000, 600, 1, 0, 0, 6, 0]])

In [ ]:
x_test.head(1)